plugins {
    id 'org.springframework.boot' version '3.2.1'
    id 'io.spring.dependency-management' version '1.1.4'
    id 'java'
}

repositories {
    mavenCentral()
    maven {
        name = "SignalBuildArtifacts"
        url = "https://build-artifacts.signal.org/libraries/maven/"
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    // implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    
    // AWS DynamoDB
    implementation platform('io.awspring.cloud:spring-cloud-aws-dependencies:3.1.0')
    implementation 'io.awspring.cloud:spring-cloud-aws-starter-dynamodb'
    
    // AWS SNS for SMS
    implementation 'io.awspring.cloud:spring-cloud-aws-starter-sns'
    // AWS SES for Email
    implementation 'io.awspring.cloud:spring-cloud-aws-starter-ses'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    
    // AWS S3 for profile pictures
    implementation 'software.amazon.awssdk:s3:2.20.26'
    
    // For OTP generation and hashing
    implementation 'commons-codec:commons-codec:1.15'
    
    // Phone number validation
    implementation 'com.googlecode.libphonenumber:libphonenumber:8.13.26'
    
    // runtimeOnly 'com.h2database:h2'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
